### ISSUE TITLE
Appreciation for the OTTP Team

### ISSUE THREAD

**Issue by 0xScratch** [opentothepublic/protocol#6]
Best problem statement to be tackled so far in the `Crypto` Category of Backdrop Build V3!

Got really convinced that the problem does exist on how a contributor doesn't get recognized for his contributions outside the platform unless he is either really known in the community or kind of in connection with many project leaders. 
It also makes it difficult for the project starters who go unnoticed despite having a good idea just because they weren't able to reach out well. This leads to a huge amount of talent goes waste!

> It also makes it difficult for the project starters who go unnoticed despite having a good idea just because they weren't able to reach out well. This leads to a huge amount of talent goes waste!

Actually, I do want to understand how OTTP solves this problem, like what are its plans?

Congratulations again!
Would like to see how `Ottp` upgrade itself for V4! 🍻

**Comment by tingwxyz** [comment]
Hi @0xScratch! Thanks for checking out our project, leaving a comment, and showing your appreciation. Agreed, it stemmed from personal experiences the team had while contributing to projects/communities as well as building in the space. 

Overall, the power is in the connections between people, contributions, and organizations, so we're focused on connecting those dots. That way, you can access all your connections and contributions on any app/client integrated with or built on OTTP.

> For example: Think about all the commits you've made on GitHub. What if the other contributors, community members, or the project owners could attest to each one? Now, you've accumulated X number of attestations from trusted people in the network or high-signal from other members in the community. Then, when you go start your own project, an app/client could curate a feed that shows projects from people who have verified contributions.

During Backdrop Build v3, we built an mini-MVP via a Farcaster Frame. People can get their OTTP ID and collaboration graph by making an attestation. Here are some immediate next steps.

**On the backend:**
- Continue to build foundational elements into the protocol, e.g. other login methods for account creation, upvote/downvote, etc.

**On the frontend:**
- Add 1-2 apps/clients in the next 4-6 weeks, so there is an interface that people can interact with.

**On the ops side:**
- Talk to communities/orgs to integrate with or build on the protocol.

I hope this helps. Please let me know if you have any other questions.

**Comment by 0xScratch** [comment]
Great steps ahead @tingwxyz 👍

Also, I was thinking of this particular scenario -> Suppose there's a user who is already connected or has an account on OTTP, if there could be a functionality by which a user doesn't need to interact with OTTP interface and his/her contributions in any project on GitHub gets automatically attested as it get merged by project's maintainers. Same could be the case for connections and other useful stuff.

Maybe you are already planning on this or probably doing it or maybe not. It's just I felt this a good one!
Will fork this repo down and try to understand this protocol in more detail and probably contribute if felt a need.

Also, there are some good suggestions:
- Try assigning a Discussions tab to this repo
- It be good if both the `contracts` and `protocols` repositories have a well defined `README`. Although, documentation is provided but still having a proper README is beneficial

**Comment by ronykris** [comment]
Thank you for sharing and taking interest in this Aryan. Attesting github
contributors in a project was something we discussed and concluded that
it's one of the many use cases of Ottp and added it to our backlog. I'm so
glad it crossed your mind too.

This was a tiny mvp using frames for backdrop v3. Therefore, plenty of
enhancements, fixes and features are yet to be worked on . We appreciate
your enthusiasm and looking forward to your contribution if it piqued your
interest.


Cheers!
